coderdojochi/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from coderdojochi.views import RegisterView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'coderdojochi.views.home', name='home'),
    url(r'^faqs/$', 'coderdojochi.views.faqs', name='faqs'),
    url(r'^donate/$','coderdojochi.views.donate',name='donate'),
    url(r'^donate/cancel/$','coderdojochi.views.donate_cancel', name='donate_cancel'),
    url(r'^donate/return/$','coderdojochi.views.donate_return', name='donate_return'),
    url(r'^donate/paypal/$', include('paypal.standard.ipn.urls')),
    url(r'^about/$','coderdojochi.views.about',name='about'),
    url(r'^privacy/$','coderdojochi.views.privacy',name='privacy'),
    url(r'^volunteer/$', 'coderdojochi.views.volunteer', name='volunteer'),
    url(r'^contact/', 'coderdojochi.views.contact', name='contact'),

    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^accounts/register/$', RegisterView.as_view(), name='register'),
    url(r'^register/enroll/$', RegisterView.as_view(enroll=True), name='register_enroll'),

    url(r'^mentors/(?P<mentor_id>[\d]+)/reject-avatar/$', 'coderdojochi.views.mentor_reject_avatar', name='mentor_reject_avatar'),
    url(r'^mentors/(?P<mentor_id>[\d]+)/approve-avatar/$', 'coderdojochi.views.mentor_approve_avatar', name='mentor_approve_avatar'),
    url(r'^mentors/(?P<mentor_id>[\d]+)/$', 'coderdojochi.views.mentor_detail', name='mentor_detail'),
    url(r'^mentors/$', 'coderdojochi.views.mentors', name='mentors'),

    url(r'^student/(?P<student_id>[\d]+)/$', 'coderdojochi.views.student_detail', name='student_detail'),

    url(r'^classes/(?P<year>[\d]+)/(?P<month>[\d]+)/$', 'coderdojochi.views.sessions', name='sessions'),
    url(r'^classes/$', 'coderdojochi.views.sessions', name='sessions'),
    url(r'^class/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?P<slug>[-\w]+)/(?P<session_id>[\d]+)/sign-up/(?P<student_id>[\d]+)/$', 'coderdojochi.views.session_sign_up', name='session_sign_up'),
    url(r'^class/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?P<slug>[-\w]+)/(?P<session_id>[\d]+)/sign-up/$', 'coderdojochi.views.session_sign_up', name='session_sign_up'),
    url(r'^class/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?P<slug>[-\w]+)/(?P<session_id>[\d]+)/enroll/$', 'coderdojochi.views.session_detail_enroll', name='session_detail_enroll'),
    url(r'^class/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?P<slug>[-\w]+)/(?P<session_id>[\d]+)$', 'coderdojochi.views.session_detail', name='session_detail'),
    url(r'^class/(?P<session_id>[\d]+)/announce/$', 'coderdojochi.views.session_announce', name='session_announce'),

    url(r'^meeting/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?P<meeting_id>[\d]+)/sign-up/$', 'coderdojochi.views.meeting_sign_up', name='meeting_sign_up'),
    url(r'^meeting/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?P<meeting_id>[\d]+)$', 'coderdojochi.views.meeting_detail', name='meeting_detail'),
    url(r'^meeting/(?P<meeting_id>[\d]+)/announce/$', 'coderdojochi.views.meeting_announce', name='meeting_announce'),

    url(r'^admin/class/(?P<session_id>[\d]+)/stats/$', 'coderdojochi.views.session_stats', name='stats'),
    url(r'^admin/class/(?P<session_id>[\d]+)/check-in/$', 'coderdojochi.views.session_check_in', name='check_in'),
    url(r'^admin/class/(?P<session_id>[\d]+)/check-in-mentors/$', 'coderdojochi.views.session_check_in_mentors', name='check_in_mentors'),
    url(r'^admin/', 'coderdojochi.views.cdc_admin', name='cdc_admin'),

    url(r'^welcome/$', 'coderdojochi.views.welcome', name='welcome'),
    url(r'^dojo/$', 'coderdojochi.views.dojo', name='dojo'),

    #override the default urls
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),

    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}),
    url(r'^login/user/(?P<user_id>.+)/$', 'loginas.views.user_login', name='loginas-user-login'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'', include('social_auth.urls')),
    url(r'^dj-admin/', include(admin.site.urls)),
    url(r'^avatar/', include('avatar.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coderdojochi/models.py
from django.conf import settings

from django.db import models

from datetime import datetime, timedelta

from django.core.validators import RegexValidator

from django.contrib.auth.models import AbstractUser

from django.utils.translation import ugettext as _
from django.utils import formats, timezone

from django.template.defaultfilters import slugify

Roles = (
    ('mentor', 'mentor'),
    ('guardian', 'guardian'),
)

class CDCUser(AbstractUser):
    role = models.CharField(choices=Roles, max_length=10, blank=True, null=True)
    admin_notes = models.TextField(blank=True, null=True)

    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(
            username=username,
            email=email,
            first_name=extra_fields[ 'first_name' ],
            last_name=extra_fields[ 'last_name' ],
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True,
                                 **extra_fields)

    def get_absolute_url(self):
        return settings.SITE_URL + '/dojo'

class Mentor(models.Model):
    user = models.ForeignKey(CDCUser)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    has_attended_intro_meeting = models.BooleanField(default=False)
    public = models.BooleanField(default=False)

    def get_approve_avatar_url(self):
        return settings.SITE_URL + '/mentors/' + str(self.id) + '/approve-avatar/'

    def get_reject_avatar_url(self):
        return settings.SITE_URL + '/mentors/' + str(self.id) + '/reject-avatar/'

    def get_absolute_url(self):
        return settings.SITE_URL + '/mentors/' + str(self.id) + '/'

    class Meta:
        verbose_name = _("mentors")
        verbose_name_plural = _("mentors")

    def __unicode__(self):
        return self.user.username

class Guardian(models.Model):
    user = models.ForeignKey(CDCUser)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)
    phone = models.CharField(max_length=50, blank=True)
    zip = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_students(self):
        students = Student.objects.filter(guardian=self)
        return students

    class Meta:
        verbose_name = _("guardian")
        verbose_name_plural = _("guardians")

    def __unicode__(self):
        return self.user.username

class Student(models.Model):
    guardian = models.ForeignKey(Guardian)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birthday = models.DateTimeField()
    gender = models.CharField(max_length=255)
    medical_conditions = models.TextField(blank=True, null=True)
    medications = models.TextField(blank=True, null=True)
    photo_release = models.BooleanField('Photo Consent', help_text="I hereby give permission to CoderDojoChi to use the student's image and/or likeness in promotional materials.", default=False)
    consent = models.BooleanField('General Consent', help_text="I hereby give consent for the student signed up above to participate in CoderDojoChi.", default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def is_registered_for_session(self, session):
        try:
            order = Order.objects.get(student=self, session=session)
            is_registered = True
        except:
            is_registered = False

        return is_registered

    def get_age(self):
        today = timezone.now()
        birthday = self.birthday
        return today.year - birthday.year - ((today.month, today.day) < (birthday.month, birthday.day))

    def get_clean_gender(self):
        if self.gender.lower() in ['male', 'm', 'boy']:
            return 'male'
        elif self.gender.lower() in ['female', 'f', 'girl']:
            return 'female'
        else:
            return 'other'

    class Meta:
        verbose_name = _("student")
        verbose_name_plural = _("students")

    def __unicode__(self):
        return self.last_name + ', ' + self.first_name

class Course(models.Model):
    code = models.CharField(max_length=255, blank=True, null=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=40, blank=True, null=True)
    description = models.TextField(blank=True, null=True, help_text="Basic HTML allowed")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name = _("course")
        verbose_name_plural = _("courses")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.code + ' | ' + self.title


class Location(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255, blank=True, null=True, verbose_name="Address 2")
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    zip = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name

def session_default_start_time():
    now = timezone.now()
    start = now.replace(hour=10, minute=0, second=0, microsecond=0)
    return start if start > now else start + timedelta(days=1)

def session_default_end_time():
    now = timezone.now()
    start = now.replace(hour=13, minute=0, second=0, microsecond=0)
    return start if start > now else start + timedelta(days=1)

class Session(models.Model):
    course = models.ForeignKey(Course)
    start_date = models.DateTimeField(default=session_default_start_time())
    end_date = models.DateTimeField(default=session_default_end_time())
    mentor_start_date = models.DateTimeField(default=session_default_start_time() - timedelta(hours=1))
    mentor_end_date = models.DateTimeField(default=session_default_end_time() + timedelta(hours=1))
    location = models.ForeignKey(Location)
    capacity = models.IntegerField(default=20)
    mentor_capacity = models.IntegerField(blank=True, null=True)
    additional_info = models.TextField(blank=True, null=True, help_text="Basic HTML allowed")
    teacher = models.ForeignKey(Mentor, related_name="session_teacher")
    mentors = models.ManyToManyField(Mentor, blank=True, null=True, related_name="session_mentors")
    waitlist_mentors = models.ManyToManyField(Mentor, blank=True, null=True, related_name="session_waitlist_mentors")
    waitlist_students = models.ManyToManyField(Student, blank=True, null=True, related_name="session_waitlist_students")
    external_enrollment_url = models.CharField(max_length=255, blank=True, null=True, help_text="When provided, local enrollment is disabled.")
    active = models.BooleanField(default=False)
    public = models.BooleanField(default=False)
    announced_date = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image_url = models.CharField(max_length=255, blank=True, null=True)
    mentors_week_reminder_sent = models.BooleanField(default=False)
    mentors_day_reminder_sent = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("session")
        verbose_name_plural = _("sessions")

    def get_absolute_url(self):
        return settings.SITE_URL + '/class/' + self.start_date.strftime("%Y/%m/%d") + '/'  + self.course.slug + '/' + str(self.id)

    def get_signup_url(self):
        return settings.SITE_URL + '/class/' + self.start_date.strftime("%Y/%m/%d") + '/'  + self.course.slug + '/' + str(self.id) + '/sign-up/'

    def get_current_orders(self, checked_in=None):
        if checked_in != None:
            if checked_in:
                orders = Order.objects.filter(session=self).exclude(check_in=None).order_by('student__last_name')
            else:
                orders = Order.objects.filter(session=self).filter(check_in=None).order_by('student__last_name')
        else:
            orders = Order.objects.filter(session=self).order_by('check_in', 'student__last_name')

        return orders

    def get_current_students(self, checked_in=None):
        if checked_in != None:
            if checked_in:
                orders = Order.objects.filter(session=self).exclude(check_in=None).values('student')
            else:
                orders = Order.objects.filter(session=self).filter(check_in=None).values('student')
        else:
            orders = Order.objects.filter(session=self).values('student')

coderdojochi/forms.py
from django import forms
from django.forms import Form, ModelForm
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from coderdojochi.models import Mentor, Guardian, Student

import html5.forms.widgets as html5_widgets

class MentorForm(ModelForm):

    bio = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Short Bio','class': 'form-control', 'rows': 5}), label='Short Bio')

    class Meta:
        model = Mentor
        fields = ('bio',)

class GuardianForm(ModelForm):

    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Phone Number','class': 'form-control'}), label='Phone Number')
    zip = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Zip Code','class': 'form-control'}), label='Zip Code')

    class Meta:
        model = Guardian
        fields = ('phone','zip',)

class StudentForm(ModelForm):

    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Jane','class': 'form-control'}), label='First Name')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Doe','class': 'form-control'}), label='Last Name')
    gender = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '','class': 'form-control'}), label='Gender')
    birthday = forms.CharField(widget=html5_widgets.DateInput(attrs={'class': 'form-control'}))
    medications = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'List any medications currently being taken.','class': 'form-control hidden', 'rows': 5}), label=format_html(u"{0} {1}", "Medications", mark_safe('<span class="btn btn-xs btn-link js-expand-student-form">expand</span>')), required=False)
    medical_conditions = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'List any medical conditions.','class': 'form-control hidden', 'rows': 5}), label=format_html(u"{0} {1}", "Medical Conditions", mark_safe('<span class="btn btn-xs btn-link js-expand-student-form">expand</span>')), required=False)
    photo_release = forms.BooleanField(widget=forms.CheckboxInput(attrs={'required': 'required'}), label="I hereby give permission to CoderDojoChi to use the student's image and/or likeness in promotional materials.")
    consent = forms.BooleanField(widget=forms.CheckboxInput(attrs={'required': 'required'}), label="I hereby give consent for the student signed up above to participate in CoderDojoChi.")

    class Meta:
        model = Student
        exclude = ('guardian', 'created_at', 'updated_at', 'active')

class ContactForm(forms.Form):

    name = forms.CharField(max_length=100, label='Your name')
    email = forms.EmailField(max_length=200, label='Your email address')
    body = forms.CharField(widget=forms.Textarea, label='Your message')
    human = forms.CharField(max_length=100, label=False, required=False)

coderdojochi/templates/about.html
{% extends "_base.html" %}

{% load i18n cache %}

{% block title %}About{% endblock %}

{% block body_class %}page-about{% endblock %}

{% block content %}
<div class="container">
    <h1>{% trans "About CoderDojoChi" %}</h1>
    <div class="row">
        <p>CoderDojoChi is a volunteer not for profit that teaches web, game, and app development to youth ages 7 to 17.</p>
        <p>Our mission is to create a fun, collaborative environment to explore <abbr title="STEM is an acronym referring to the academic disciplines of science, technology, engineering, and mathematics.">STEM</abbr>. Through challenging play, youth can build memorable experiences with mentors. All classes are 100% free to attend thanks to your generous <a title="Donate now" href="{% url 'donate' %}">donations</a>.</p>
        <p>Ali Karbassi founded CoderDojoChi in 2013. It has grown to more than {{ mentor_count }} active mentors teaching over {{ students_served }} students. We host twice monthly workshops with dozens of youth, and reach hundreds of families across the Greater Chicago area.</p>
        <p>CoderDojoChi is an 501(c)(3) tax-exempt nonprofit organization in the United States.</p>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h2>Contact Us</h2>
            <form method="post" action="{% url 'contact' %}" _lpchecked="1">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" for="id_name">Your name</label>
                    <input class="form-control" id="id_name" maxlength="100" name="name" placeholder="Your name" required="required" title="" type="text">
                </div>
                <div class="form-group">
                    <label class="control-label" for="id_email">Your email address</label>
                    <input class="form-control" id="id_email" maxlength="200" name="email" placeholder="Your email address" required="required" title="" type="email">
                </div>
                <div class="form-group">
                    <label class="control-label" for="id_body">Your message</label>
                    <textarea class="form-control" cols="40" id="id_body" name="body" placeholder="Your message" required="required" rows="10" title=""></textarea>
                </div>
                <div class="form-group">
                    <input class="form-control" id="id_human" maxlength="100" name="human" title="" type="text">
                </div>
                <input class="btn-cdc btn-cdc-success" type="submit" value="Submit">
            </form>
        </div>
        <div class="col-sm-5 col-sm-offset-1">
            <br>
            <div>
                <a class="icon-action" href="{% url 'volunteer' %}">
                    <span class="icon-volunteer fa fa-fw fa-group"></span>
                </a>
                <h1 class="text-center">Volunteer</h1>
                <p>We're looking for people who believe they can make a difference by exposing the youth to the world of coding.</p>
            </div>
            <div>
                <a class="icon-action" href="{% url 'donate' %}">
                    <span class="icon-donation fa fa-fw"></span>
                </a>
                <h1 class="text-center">Donate</h1>
                <p>Funding goes 100% towards equipment and food for youth, attendees, and mentors.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

coderdojochi/templates/donate.html
{% extends "_base.html" %}

{% load i18n cache %}

{% block title %}Donate{% endblock %}

{% block body_class %}page-donate{% endblock %}

{% block content %}

<div class="hero">
    <div class="container">
        <h1 class="title">Donate Today!</h1>

        <ul class="list-inline amount-buttons">
            <li><button class="btn-cdc btn-cdc-inverse" data-value="25">$25</button></li>
            <li><button class="btn-cdc btn-cdc-inverse" data-value="50">$50</button></li>
            <li><button class="btn-cdc btn-cdc-inverse" data-value="100">$100</button></li>
            <li><button class="btn-cdc btn-cdc-inverse" data-value="150">$150</button></li>
            <li><button class="btn-cdc btn-cdc-inverse" data-value="other">Other</button></li>
        </ul>
        <div class="amount-actual">
            <span class="dollar">$</span>
            <input type="text" class="form-control input-lg" maxlength="6">
        </div>
        <div class="personal-info">
            <h3 class="text-center">Please tell us a little about yourself</h3>
            <div class="form-group">
                <input type="text" id="firstNameInput" class="form-control input-lg" placeholder="First name e.g. William">
            </div>
            <div class="form-group">
                <input type="text" id="lastNameInput"  class="form-control input-lg" placeholder="Last name e.g. Gates">
            </div>
            <div class="form-group">
                <input type="email" id="emailInput"  class="form-control input-lg" placeholder="Email Address e.g. bill.gates@microsoft.com">
            </div>
            <h3 class="text-center">We will email you a receipt<br>(includes tax exempt information)</h3>

            <button class="btn-cdc btn-cdc-inverse btn-do-it" disabled>Do it.</button>
        </div>
    </div>
</div>

<div class="container">
    <h2>{% trans "You can help!" %}</h2>
    <p>CoderDojoChi is a registered non-profit organization supported entirely by...you! Please help us continue our mission by donating a small amount to our cause. Thank you! </p>

    {{ form.render }}

</div>

{% endblock %}

{% block extra_script %}
<script>
    $(function() {
        var $donateForm = $('form');
        var $amountButtons = $('.amount-buttons:first');
        var $donateButton = $('.btn-do-it:first');
        var $donateAmount = $('#id_amount');
        var $amountActual = $('.amount-actual:first');
        var $amountActualField = $('.form-control', $amountActual);
        var $personalInfo = $('.personal-info:first');
        var $firstNameInput = $('#firstNameInput');
        var $lastNameInput = $('#lastNameInput');
        var $emailInput = $('#emailInput');
        var $invoiceNumber = $('#id_invoice');
        var $paymentFirstName = $('#id_first_name');
        var $paymentLastName = $('#id_last_name');

        var amountButtonClick = function() {
            var $clicked = $(this);
            var clickedValue = $clicked.data('value');

            $('.active', $amountButtons).removeClass('active');
            $clicked.addClass('active');
            $donateButton.attr('disabled', false);

            // show personal information fields
            $personalInfo.show();

            if (clickedValue === 'other') {
                $amountActual.show();
                $amountActualField.focus();
            } else {
                $amountActual.hide();
                $('.form-control:first', $personalInfo).focus();
            }

            ga('send', 'event', 'button', 'click', 'donation form amount selected', clickedValue);
        };

        var donateFormSubmit = function(e) {
            $donateButton.trigger('click');
        };

        var donateButtonClick = function() {

            var $selectedAmountButton = $('.active', $amountButtons);
            var selectedAmount = $selectedAmountButton.data('value');
            var emailTest = /^[A-Z0-9._%+-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i;
            var formData;

            if(selectedAmount === 'other') {

                var customAmount = $amountActualField.val();

                if(customAmount.length){
                    selectedAmount = parseInt(customAmount);
                } else {
                    $amountActual.addClass('has-error');
                    $amountActualField.focus();
                    return false;
                }
            }

            // set donation amount
            $donateAmount.val(selectedAmount);

            if(!$firstNameInput.val()) {
                showError($firstNameInput, 'First name is required to receive a receipt.');
                return false;
            }

            if(!$lastNameInput.val()) {
                showError($lastNameInput, 'Last name is required to receive a receipt.');
                return false;
            }

            if(!$emailInput.val() || !emailTest.test($emailInput.val())) {
                showError($emailInput, 'A valid email address is required to receive a receipt.');
                return false;
            }

            formData = {
                first_name: $firstNameInput.val(),
                last_name: $lastNameInput.val(),
                email: $emailInput.val(),
                amount: parseInt(selectedAmount),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }

            ga('send', 'event', 'button', 'click', 'donation form donate button clicked');

            // submit donation record before submitting
            $.post('/donate/', formData, function(response) {
                if(response !== 'failed') {
                    $paymentFirstName.val(formData.first_name);
                    $paymentLastName.val(formData.last_name);
                    $invoiceNumber.val(response);
                    $donateForm.off('submit');
                    $donateForm.submit();
                } else {
                    alert('An error occured, please refresh the page and try again.')
                }
            });
        };

        var showError = function ($input, message) {
            $('.has-error', $personalInfo).removeClass('has-error');
            $('.alert-danger', $personalInfo).remove();
            $input.closest('.form-group')
                .addClass('has-error')
                .before('<div class="alert alert-danger">' + message + '</div>');
        };

        $donateForm.submit(donateFormSubmit);

        $amountButtons
            .on('click', 'button', amountButtonClick);

        $donateButton
            .on('click', donateButtonClick);

        // tracking code

        $firstNameInput.on('focus', function() {
            ga('send', 'event', 'input', 'focus', 'donation form first name input focus');
        });

        $lastNameInput.on('focus', function() {
            ga('send', 'event', 'input', 'focus', 'donation form last name input focus');
        });

        $emailInput.on('focus', function() {
            ga('send', 'event', 'input', 'focus', 'donation form email input focus');
        });

        $amountActualField.on('focus', function() {
            ga('send', 'event', 'input', 'focus', 'donation form custom amount input focus');
        });

    });
</script>
{% endblock %}

coderdojochi/templates/mentors.html
{% extends "_base.html" %}
{% load avatar_tags humanize %}

{% block title %}My Dojo{% endblock %}

{% block body_class %}page-mentors{% endblock %}

{% block content %}

<div class="container">

    <h1>Meet Our Mentors <a href="{% url 'register' %}" class="btn-cdc">Join us now!</a></h1>

    <div class="row mentors">
        {% for mentor in mentors %}
            {% if mentor.public == True %}
        <div class="col-xs-12 col-sm-4 col-md-3">
            <a href="{% url 'mentor_detail' mentor.id %}" class="thumbnail">
                {% avatar mentor.user 175 %}
                <span class="caption text-center">{{ mentor.first_name }} {{ mentor.last_name }}</span>
            </a>
        </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

coderdojochi/templates/session-check-in-mentors.html
{% extends "_base.html" %}

{% load i18n avatar_tags coderdojochi_extras %}

{% block title %}{% if session.course.code %}{{ session.course.code }} | {% endif %}{{ session.course.title }}{% endblock %}

{% block body_class %}page-cdc-admin{% endblock %}

{% block topnav %}{% endblock %}

{% block content %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'cdc_admin' %}">CoderDojoChi Admin</a></li>
        <li><a href="{{ session.get_absolute_url }}">{{ session.start_date|date }} - {{ session.course.title }}</a></li>
        <li class="active">Class Check-in Mentors</li>
    </ol>
    <div class="alert alert-warning">Coming Soon :)</div>
</div>
{% endblock %}


{% block footer_base %}{% endblock %}